language: java
jdk:
        - openjdk11

branches:
        only:
                - master

# Travis CI 서버의 Homcache:
cache:
        directories:
                - $HOME/.m2

#CI 실행 완료 시 메일로 알림
notifications:
        email:
                recipients:
                        - kdm97912@gmail.com
